export enum AppRoute {
  GUEST = 'guest',
  DASHBOARD_HOME = 'dashboard',
  USER_LIST   = 'dashboard/user',
  USER_DETAIL = 'dashboard/user/detail/',
  USER_CREATE = 'dashboard/user/create',
  VEHICULE_LIST   = 'dashboard/vehicule',
  VEHICULE_DETAIL = 'dashboard/vehicule/detail/',
  VEHICULE_CREATE = 'dashboard/vehicule/create',
  PRESTATAIRE_LIST    = 'dashboard/prestataire',
  PRESTATAIRE_DETAIL  = 'dashboard/prestataire/detail/',
  PRESTATAIRE_CREATE  = 'dashboard/prestataire/create',
  GRADE_LIST    = 'dashboard/grade',
  GRADE_DETAIL  = 'dashboard/grade/detail/',
  GRADE_CREATE  = 'dashboard/grade/create',
  SITE_LIST   = 'dashboard/site',
  SITE_DETAIL = 'dashboard/site/detail/',
  SITE_CREATE = 'dashboard/site/create',
  STATUS_LIST   = 'dashboard/status',
  STATUS_DETAIL = 'dashboard/status/detail/',
  STATUS_CREATE = 'dashboard/status/create',
  NUMBERPLATE_LIST    = 'dashboard/numberplate',
  NUMBERPLATE_DETAIL  = 'dashboard/numberplate/detail/',
  NUMBERPLATE_CREATE  = 'dashboard/numberplate/create',
  TACHYGRAPHE_LIST    = 'dashboard/tachygraphe',
  TACHYGRAPHE_DETAIL  = 'dashboard/tachygraphe/detail/',
  TACHYGRAPHE_CREATE  = 'dashboard/tachygraphe/create',
}
