export enum AppRoute {
  GUEST = 'guest',
  DASHBOARD_HOME = 'dashboard',
  USER_LIST = 'dashboard/user/list',
  USER_DETAIL = 'dashboard/user/detail/',
  VEHICULE_LIST = 'dashboard/vehicule/list',
  VEHICULE_DETAIL = 'dashboard/vehicule/detail/',
  PRESTATAIRE_LIST = 'dashboard/prestataire/list',
  PRESTATAIRE_DETAIL = 'dashboard/prestataire/detail/',
  GRADE_LIST = 'dashboard/grade/list',
  GRADE_DETAIL = 'dashboard/grade/detail/',
  SITE_LIST = 'dashboard/site/list',
  SITE_DETAIL = 'dashboard/site/detail/',
  STATUS_LIST = 'dashboard/status/list',
  STATUS_DETAIL = 'dashboard/status/detail/',
  NUMBERPLATE_LIST = 'dashboard/numberplate/list',
  NUMBERPLATE_DETAIL = 'dashboard/numberplate/detail/',
  TACHYGRAPHE_LIST = 'dashboard/tachygraphe/list',

}
