export enum MenuItemType{
  USER_DETAIL         = 'USER_DETAIL',
  VEHICULE_DETAIL     = 'VEHICULE_DETAIL',
  ADDRESS_DETAIL      = 'ADDRESS_DETAIL',
  APPOINTMENT_DETAIL  = 'APPOINTMENT_DETAIL',
  GRADE_DETAIL        = 'GRADE_DETAIL',
  NUMBERPLATE_DETAIL  = 'NUMBERPLATE_DETAIL',
  PERIOD_DETAIL       = 'PERIOD_DETAIL',
  PRESTATAIRE_DETAIL  = 'PRESTATAIRE_DETAIL',
  SITE_DETAIL         = 'SITE_DETAIL',
  STATUS_DETAIL       = 'STATUS_DETAIL',
  TACHYGRAPHE_DETAIL  = 'TACHYGRAPHE_DETAIL',
}
