export enum MenuItemType {
  GUEST = 'GUEST',
  DASHBOARD_HOME = 'DASHBOARD_HOME',
  /* USER */
  USER_LIST = 'USER_LIST',
  USER_DETAIL = 'USER_DETAIL',
  USER_CREATE = 'USER_CREATE',
  /* VEHICULE */
  VEHICULE_LIST = 'VEHICULE_LIST',
  VEHICULE_DETAIL = 'VEHICULE_DETAIL',
  VEHICULE_CREATE = 'VEHICULE_CREATE',
  /* ADDRESS */
  ADDRESS_DETAIL = 'ADDRESS_DETAIL',
  /* APPOINTMENT */
  APPOINTMENT_DETAIL = 'APPOINTMENT_DETAIL',
  /* GRADE */
  GRADE_LIST = 'GRADE_LIST',
  GRADE_DETAIL = 'GRADE_DETAIL',
  GRADE_CREATE = 'GRADE_CREATE',
  /* NUMBERPLATE */
  NUMBERPLATE_LIST = 'NUMBERPLATE_LIST',
  NUMBERPLATE_DETAIL = 'NUMBERPLATE_DETAIL',
  NUMBERPLATE_CREATE = 'NUMBERPLATE_CREATE',
  /* PERIOD */
  PERIOD_DETAIL = 'PERIOD_DETAIL',
  /* PRESTATAIRE */
  PRESTATAIRE_LIST = 'PRESTATAIRE_LIST',
  PRESTATAIRE_DETAIL = 'PRESTATAIRE_DETAIL',
  PRESTATAIRE_CREATE = 'PRESTATAIRE_CREATE',
  /* SITE */
  SITE_LIST = 'SITE_LIST',
  SITE_DETAIL = 'SITE_DETAIL',
  SITE_CREATE = 'SITE_CREATE',
  /* STATUS */
  STATUS_LIST = 'STATUS_LIST',
  STATUS_DETAIL = 'STATUS_DETAIL',
  STATUS_CREATE = 'STATUS_CREATE',
  /* TACHYGRAPHE */
  TACHYGRAPHE_DETAIL = 'TACHYGRAPHE_DETAIL',




}
